- hosts: nodes
  become: yes
  tasks:
  - name: Ensure docker is installed
    apt:
      name: docker.io
      state: latest

  - name: Ensure docker compose is installed
    apt:
      name: docker-compose
      state: latest

  - name: Added user docker group
    user:
      name: vagrant
      groups: docker
